### ISSUE TITLE
想要提交结果到官网应该选择哪个文件呢？

### ISSUE THREAD

**Issue by Jingyilang** [basketballandlearn/MRC_Competition_Dureader#11]

**Comment by basketballandlearn** [comment]
官方的要提交test文件，这得去官方下载

**Comment by Jingyilang** [comment]
> 官方的要提交test文件，这得去官方下载

test文件去官方下载是指？我已经把data替换成原来的全部数据了

**Comment by basketballandlearn** [comment]
你好！
    比赛时提交的是test文件，官方现在好像提交不了了，你本地测试就行




------------------ 原始邮件 ------------------
发件人: "zzuczy"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 下午4:26
收件人: "basketballandlearn/Dureader-Bert"<Dureader-Bert@noreply.github.com>;
抄送: "暂无"<1643230637@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [basketballandlearn/Dureader-Bert] 想要提交结果到官网应该选择哪个文件呢？ (#11)



 
官方的要提交test文件，这得去官方下载
  
test文件去官方下载是指？我已经把data替换成原来的全部数据了

**Comment by Jingyilang** [comment]
> 你好！ 比赛时提交的是test文件，官方现在好像提交不了了，你本地测试就行
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "zzuczy"<notifications@github.com>; 发送时间: 2019年8月7日(星期三) 下午4:26 收件人: "basketballandlearn/Dureader-Bert"<Dureader-Bert@noreply.github.com>; 抄送: "暂无"<1643230637@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [basketballandlearn/Dureader-Bert] 想要提交结果到官网应该选择哪个文件呢？ (#11) 官方的要提交test文件，这得去官方下载 test文件去官方下载是指？我已经把data替换成原来的全部数据了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

好的，多谢！
