### ISSUE TITLE
运行sh run.sh --para_extraction时报错

### ISSUE THREAD

**Issue by liping-apple** [basketballandlearn/MRC_Competition_Dureader#13]
PROCESS_NAME="$1"
case $PROCESS_NAME in  # 这个位置报错
    --para_extraction)
    # Start paragraph extraction 
    if [ ! -d ../data ]; then
        echo "Please download the preprocessed data first (See README - Preprocess)"
        exit 1
    fi
    paragraph_extraction  ../data  ../data/extracted
    ;;
    --prepare|--train|--evaluate|--predict)
        # Start Paddle baseline
        python run.py $@
    ;;
    *)
        echo $"Usage: $0 {--para_extraction|--prepare|--train|--evaluate|--predict}"
esac

运行sh run.sh --para_extraction时报错
run.sh: 35: run.sh: Syntax error: word unexpected (expecting "in")
感觉语法也没问题，找来找去都没搞懂是哪里错了，有大佬知道吗？

**Comment by luohm111** [comment]
我遇到的是__init__() got an unexpected keyword argument 'encoding',因为json.dumps没encoding这个参数，所以把encoding='utf8'这个去掉就可以
