### ISSUE TITLE
squad_convert_examples_to_features

### ISSUE THREAD

**Issue by sxlyiyiyi** [basketballandlearn/MRC_Competition_Dureader#32]
请问squad_convert_examples_to_features需要运行多久才可以转换完成

**Comment by basketballandlearn** [comment]
看你的数据量，可以通过--threads指定数据处理的线程数~

**Comment by sxlyiyiyi** [comment]
我使用了threads=6，json文件大概30多m，要跑20个小时，这是不是不正常

**Comment by sxlyiyiyi** [comment]
每一个个context都挺长的

**Comment by basketballandlearn** [comment]
参考：a100单卡，5w数据，threads=12，跑2小时



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月18日(星期二) 中午11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [basketballandlearn/MRC_Competition_Dureader] squad_convert_examples_to_features (#32)





 
我使用了threads=6，json文件大概30多m，要跑20个小时，这是不是不正常

**Comment by renxingkai** [comment]
> 我使用了threads=6，json文件大概30多m，要跑20个小时，这是不是不正常

我的也好慢，几十个小时，纯拼CPU了
