### ISSUE TITLE
网上收集的大量中文MRC数据

### ISSUE THREAD

**Issue by TccccD** [basketballandlearn/MRC_Competition_Dureader#40]
你好，问下在readme里提到的网上收集的大量中文MRC数据，这份数据集能否分享一下，感谢！

**Comment by r09944035vsfu1** [comment]
如果不方便公布数据，根据README的介绍来看

想请问总共使用哪些公开的MRC资料集？
以及自行爬取的来源网站大概有哪些呢？（很想了解一下要找哪些网站爬资料）

谢谢！

**Comment by basketballandlearn** [comment]
数据这块涉及很多问题，还是不公布为妙

**Comment by Lijiadong** [comment]
请问一下是否包含CMRC2018的语料？
